export enum PageState {
    Default,
    Pending,
    Connected,
    Processing,
    InternalError,
    Retry,
    Wrong,
    Sending,
    Cancelled,
    NotMined,
    Ok,
    Win,
    ParseFailed,
    ErrParseFailed,
    InvalidLevel,
    MissingFunds,
    Unexpected
}